[package]
name = "coal-mind-linear-regression"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"

[dev-dependencies]
# criterion = "0.5"

# [[bench]]
# name = "benchmarks"
# harness = false